version: '4'

services:
  postgres:
    image: postgres
    volumes:
      - C:/Users/gabri/Downloads/Dockerfile/adaptare/api/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5435:5432"
    networks:
      - mynetwork
    env_file:
      - env_file.env
networks:
  mynetwork: