version: '4'

services:
  postgres:
    image: postgres
    volumes:
      - ./Dockerfile/adaptare/api/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5435:5432"
    networks:
      - adptare
    env_file:
      - env_file.env
networks:
  adptare:
    external: true
